# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f13e6a435f8dbd30274e1d4713fb19361aa2481025bd83aafbceafaf54dee851032e1f27a7b1cdc30f6dd310e1ba1e2292b7b2af46e3451d53d8be03d5cd05bf

test:
  secret_key_base: dd1cf9edd9a2dc7abd7fd2107f6d6c93805559dd2bddaf5ab7e4345307c207355a741fb4e32f05afa9a7b69f031a20968cc5a1c2f0162d280e5559e05e99b48a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
